apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-user.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "backend-user.name" . }}
    helm.sh/chart: {{ include "backend-user.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "backend-user.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "backend-user.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
          - name: NODE_ENV
            valueFrom:
              configMapKeyRef:
                name: questcode
                key: NODE_ENV
          - name: MONGO_URI
            valueFrom:
              secretKeyRef:
                name: questcode
                key: MONGO_URI
          - name: SECRET_OR_KEY
            valueFrom:
              secretKeyRef:
                name: questcode
                key: SECRET_OR_KEY
          livenessProbe:
            httpGet:
              path: /api/profile/test
              port: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: /api/profile/test
              port: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
