apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-scm
  labels:
    app: backend-scm
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-scm
  template:
    metadata:
      labels:
        app: backend-scm
    spec:
      containers:
      - name: backend-scm
        image: rodrigogrohl/questcode-backend-scm:0.1.2
        ports:
        - containerPort: 3030
        env:
        - name: NODE_ENV
          # value: "staging"
          valueFrom:
            configMapKeyRef:
              name: questcode
              key: NODE_ENV
        - name: GITHUB_CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: questcode
              key: GITHUB_CLIENT_ID
        - name: GITHUB_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: questcode
              key: GITHUB_CLIENT_SECRET